[
   RecommendConfig                                        -- KW["recommend"] _1 KW["{"] _2 KW["}"],
   RecommendConfig.2:iter-star                            -- _1,
   RecommendArgument                                      -- _1 KW["="] _2,
   RecommendConfigStaticOrder                             -- KW["recommenderStaticOrder"] _1 KW["{"] _2 _3 _4 _5 _6 _7 _8 _9 KW["}"],
   RecommendUser                                          -- _1,
   RecommendItem                                          -- _1,
   RecommendValue                                         -- _1,
   RecommendAlgorithm                                     -- _1,
   RecommendNeighborAlg                                   -- _1,
   RecommendNeighborSize                                  -- _1,
   RecommendType                                          -- _1,
   RecommendSchedule                                      -- _1,
   FullTextAnalyzer                                       -- _1 KW["analyzer"] _2 KW["{"] _3 KW["}"],
   FullTextAnalyzer.1:opt                                 -- _1,
   DualFullTextAnalyzerBodyDef                            -- _1 KW["{"] _2 KW["}"] _3 KW["{"] _4 KW["}"],
   FullTextAnalyzerBodyDef                                -- _1 _2 _3,
   FullTextAnalyzerBodyDef.1:iter-star                    -- _1,
   FullTextAnalyzerBodyDef.3:iter-star                    -- _1,
   CharFilter                                             -- KW["charfilter"] KW["="] _1 KW["("] _2 KW[")"],
   CharFilter.2:iter-star-sep                             -- _1 KW[","],
   CharFilterNoArgs                                       -- KW["charfilter"] KW["="] _1,
   Tokenizer                                              -- KW["tokenizer"] KW["="] _1 KW["("] _2 KW[")"],
   Tokenizer.2:iter-star-sep                              -- _1 KW[","],
   TokenizerNoArgs                                        -- KW["tokenizer"] KW["="] _1,
   TokenFilter                                            -- KW["tokenfilter"] KW["="] _1 KW["("] _2 KW[")"],
   TokenFilter.2:iter-star-sep                            -- _1 KW[","],
   TokenFilterNoArgs                                      -- KW["tokenfilter"] KW["="] _1,
   Argument                                               -- _1 KW["="] _2,
   SearchableAnno                                         -- KW["searchable"],
   SearchableAnno                                         -- KW["searchable"] KW["("] _1 KW[")"],
   SearchableAnno.1:iter-star-sep                         -- _1 KW[","],
   SearchNamespaceAnno                                    -- KW["searchnamespace"],
   SearchableAnnoBoost                                    -- _1 KW["*"] _2,
   SA-Argument                                            -- _1 KW["="] _2,
   Autocomplete-Argument                                  -- KW["autocomplete"],
   Spellcheck-Argument                                    -- KW["spellcheck"],
   Numeric-Argument                                       -- KW["numeric"],
   DefaultSF-Argument                                     -- KW["default"],
   SearchMappingEmbedded                                  -- KW["searchmapping"] KW["{"] _1 KW["}"],
   SearchMappingEmbedded.1:iter-star                      -- _1,
   SearchMapping                                          -- KW["searchmapping"] _1 KW["{"] _2 KW["}"],
   SearchMapping.2:iter-star                              -- _1,
   SearchNamespaceMapping                                 -- KW["namespace"] KW["by"] _1,
   SearchNamespaceMapping                                 -- KW["namespace"] KW["by"] _1 KW[";"],
   SearchFieldMapping                                     -- _1 _2 _3 KW[";"],
   SearchFieldMapping.1:opt                               -- _1,
   SearchFieldMapping.3:iter-star                         -- _1,
   SearchFieldMapping                                     -- _1 KW["index"] _2 _3 KW[";"],
   SearchFieldMapping.1:opt                               -- _1,
   SearchFieldMapping.3:iter-star                         -- _1,
   SearchFieldMapping                                     -- _1 _2 _3,
   SearchFieldMapping.1:opt                               -- _1,
   SearchFieldMapping.3:iter-star                         -- _1,
   SearchFieldMapping                                     -- _1 KW["index"] _2 _3,
   SearchFieldMapping.1:opt                               -- _1,
   SearchFieldMapping.3:iter-star                         -- _1,
   FieldName                                              -- KW["as"] _1,
   AnalyzerName                                           -- KW["using"] _1,
   Boost                                                  -- KW["boosted"] KW["to"] _1,
   TargetEntity                                           -- KW["for"] KW["subclass"] _1,
   Boost                                                  -- KW["*"] _1,
   SearchMappingAnno                                      -- KW["("] _1 KW[")"],
   SearchMappingAnno.1:iter-star-sep                      -- _1 KW[","],
   EmbeddedDepth                                          -- KW["depth"] _1,
   EmbeddedDepth                                          -- KW["with"] KW["depth"] _1,
   SearcherInit                                           -- KW["search"] _1 _2,
   SearcherInit.2:iter-star                               -- _1,
   SearcherRefMod                                         -- KW["~"] _1 _2,
   SearcherRefMod.2:iter                                  -- _1,
   QueryDef                                               -- KW["matching"] _1 _2,
   QueryDef.1:opt                                         -- _1,
   Start                                                  -- KW["start"] _1,
   MaxResults                                             -- KW["limit"] _1,
   SortBy                                                 -- V  [H  [KW["sort"] KW["by"]] _1],
   SortBy.1:iter-sep                                      -- _1 KW[","],
   ConstraintFilter                                       -- V  [H  [KW["where"]] _1],
   ConstraintFilter.1:iter-sep                            -- _1 KW[","],
   FacetDef                                               -- V  [H  [KW["with"] KW["facet"]] _1],
   FacetDef.1:iter-sep                                    -- _1 KW[","],
   FacetDef                                               -- V  [H  [KW["with"] KW["facets"]] _1],
   FacetDef.1:iter-sep                                    -- _1 KW[","],
   SearchAttributes                                       -- KW["["] _1 KW["]"],
   SearchAttributes.1:iter-star-sep                       -- _1 KW[","],
   NamespaceConstraint                                    -- KW["in"] KW["namespace"] _1,
   NoLucene                                               -- KW["nolucene"],
   Lucene                                                 -- KW["lucene"],
   DefaultAnd                                             -- KW["strict"] KW["matching"],
   DefaultOr                                              -- KW["loose"] KW["matching"],
   FieldsConstraint                                       -- _1 KW[":"],
   FieldsConstraint.1:iter-sep                            -- _1 KW[","],
   QueryConstraint                                        -- _1,
   QueryConstraint.1:iter-sep                             -- _1 KW[","],
   FacetDef                                               -- KW["("] _1 KW[","] _2 KW[")"],
   FieldFilterConstraint                                  -- _1 KW["="] _2,
   FacetFilterConstraint                                  -- _1,
   GroupDef                                               -- _1 KW["("] _2 KW[")"],
   GroupDef.1:opt                                         -- _1,
   GroupDef.2:iter-sep                                    -- _1 KW[","],
   TermDef                                                -- _1 _2 _3,
   TermDef.1:opt                                          -- _1,
   TermDef.3:opt                                          -- _1,
   RangeDef                                               -- _1 KW["("] _2 KW["to"] _3 KW[")"],
   RangeDef.1:opt                                         -- _1,
   RangeDef                                               -- _1 _2 KW["to"] _3,
   RangeDef.1:opt                                         -- _1,
   Must                                                   -- KW["+"],
   MustNot                                                -- KW["-"],
   Slop                                                   -- KW["~"] _1,
   SortDef                                                -- _1 _2,
   SortDef.2:opt                                          -- _1,
   Ascending                                              -- KW["asc"],
   Ascending                                              -- KW["ascending"],
   Descending                                             -- KW["desc"],
   Descending                                             -- KW["descending"],
   HighlightTags                                          -- KW["highlight"] _1 KW["for"] _2 KW["on"] _3 KW["surround"] KW["with"] KW["("] _4 KW[","] _5 KW[")"],
   Highlight                                              -- KW["highlight"] _1 KW["for"] _2 KW["on"] _3,
   SearchResults                                          -- KW["get"] KW["results"] KW["("] _1 KW[")"],
   FacetResults                                           -- KW["get"] KW["facets"] KW["("] _1 KW[","] _2 KW[")"],
   AllFacetResults                                        -- KW["get"] KW["all"] KW["facets"] KW["("] _1 KW[","] _2 KW[")"],
   SearchResultsSize                                      -- KW["get"] KW["size"] KW["("] _1 KW[")"],
   SearchTimeString                                       -- KW["get"] KW["searchtime"] KW["("] _1 KW[")"],
   SearchTimeMS                                           -- KW["get"] KW["searchtimems"] KW["("] _1 KW[")"],
   SearchTimeSec                                          -- KW["get"] KW["searchtimesec"] KW["("] _1 KW[")"],
   SearchFieldRef                                         -- KW["~"] _1,
   Suggest                                                -- _1 _2 _3,
   Suggest.3:iter                                         -- _1,
   AutoComplete                                           -- KW["completions"],
   SpellCheck                                             -- KW["corrections"],
   Similarity                                             -- KW["similarity"] _1,
   SuggestTerm                                            -- KW["matching"] _1 _2,
   ServiceFunction                                        -- KW["service"] _1 KW["("] _2 KW[")"] _3,
   ServiceFunction.2:iter-star-sep                        -- _1 KW[","],
   Weeks                                                  -- _1 KW["weeks"],
   Days                                                   -- _1 KW["days"],
   Hours                                                  -- _1 KW["hours"],
   Minutes                                                -- _1 KW["minutes"],
   Seconds                                                -- _1 KW["seconds"],
   Milliseconds                                           -- _1 KW["milliseconds"],
   TimeInterval                                           -- _1,
   TimeInterval.1:iter-star                               -- _1,
   InvokeEvery                                            -- KW["invoke"] _1 KW["every"] _2,
   Test                                                   -- KW["test"] _1 _2,
   SimpleSort                                             -- _1,
   GenericSort                                            -- _1 KW["<"] _2 KW[">"],
   GenericSort.2:iter-sep                                 -- _1 KW[","],
   RefSort                                                -- KW["Ref"] KW["<"] _1 KW[">"],
   TypeDef                                                -- KW["type"] _1 KW["{"] _2 KW["}"],
   TypeDef.2:iter-star                                    -- _1,
   TypeDefAnno                                            -- _1,
   NativeClassFunctionFromStatic                          -- _1 KW["as"] _2,
   ThrowStatement                                         -- KW["throw"] _1 KW[";"],
   ThrowStatement.1:iter-sep                              -- _1 KW[","],
   ThrowTemplate                                          -- V  [H  [KW["throw"]] _1],
   ThrowTemplate.1:iter-sep                               -- _1 KW[","],
   TryStatement                                           -- KW["try"] _1 _2,
   TryStatement.2:iter                                    -- _1,
   TryTemplate                                            -- KW["try"] _1 _2,
   TryTemplate.2:iter                                     -- _1,
   Catch                                                  -- KW["catch"] KW["("] _1 KW[":"] _2 KW[")"] _3,
   Dispatch                                               -- KW["dispatch"] KW["{"] _1 _2 KW["}"],
   Dispatch.1:iter-star                                   -- _1,
   DispatchEntry                                          -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   DispatchEntry.2:iter-star-sep                          -- _1 KW[","],
   DispatchEntry.3:iter-star                              -- _1,
   DispatchEntryNoArg                                     -- _1 KW["{"] _2 KW["}"],
   DispatchEntryNoArg.2:iter-star                         -- _1,
   DispatchEntity                                         -- _1 KW[":"] _2 KW["{"] _3 KW["}"],
   DispatchEntity.3:iter-star                             -- _1,
   DispatchDefault                                        -- KW["default"] KW["{"] _1 KW["}"],
   DispatchDefault.1:iter-star                            -- _1,
   None                                                   -- ,
   DispatchNavigate                                       -- KW["navigate"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   DispatchNavigate.1:iter-sep                            -- _1 KW["/"],
   DispatchNavigate.2:iter-star                           -- _1,
   DispatchNavigateButton                                 -- KW["navigate"] KW["("] _1 KW[","] _2 KW[")"],
   DispatchNavigateButton.2:iter-sep                      -- _1 KW["/"],
   DispatchNavigateCall                                   -- _1 KW["("] _2 KW[")"],
   DispatchNavigateCall.2:iter-star-sep                   -- _1 KW[","],
   DispatchNavigateCallNoArg                              -- _1,
   NativeFunction                                         -- KW["native"] KW["function"] _1 KW["("] _2 KW[")"] KW[":"] _3 KW[";"],
   NativeFunction.2:iter-star-sep                         -- _1 KW[","],
   NativeClass                                            -- KW["native"] KW["class"] _1 _2 _3 KW["{"] _4 KW["}"],
   NativeClass.4:iter-star                                -- _1,
   NativeClassAlias                                       -- KW["as"] _1,
   None                                                   -- ,
   NativeClassSuper                                       -- KW[":"] _1,
   None                                                   -- ,
   NativeClassProperty                                    -- _1 KW[":"] _2,
   NativeClassFunction                                    -- _1 _2 KW["("] _3 KW[")"] _4,
   NativeClassFunction.3:iter-star-sep                    -- _1 KW[","],
   NativeClassFunctionReturn                              -- KW[":"] _1,
   None                                                   -- ,
   NativeClassFunctionStatic                              -- KW["static"],
   None                                                   -- ,
   NativeClassFunctionFromStatic                          -- _1 KW["as"] _2,
   NativeClassConstructor                                 -- KW["constructor"] KW["("] _1 KW[")"],
   NativeClassConstructor.1:iter-star-sep                 -- _1 KW[","],
   NativeGenericType                                      -- _1 KW["<"] _2 KW[">"],
   NativeGenericType.2:iter-star-sep                      -- _1 KW[","],
   NativeSimpleType                                       -- _1,
   ValidationAnnoLength                                   -- KW["length"] KW["("] _1 KW[","] _2 KW[")"],
   ValidationAnnoMinLength                                -- KW["minlength"] KW["("] _1 KW[")"],
   ValidationAnnoMaxLength                                -- KW["maxlength"] KW["("] _1 KW[")"],
   ValidationAnnoNotEmpty                                 -- KW["notempty"],
   ValidationAnnoEmail                                    -- KW["email"],
   ValidationAnnoCreditCardNumber                         -- KW["creditcardnumber"],
   ValidationAnnoEAN                                      -- KW["EAN"],
   ValidationAnnoPattern                                  -- KW["pattern"] KW["("] _1 KW[")"],
   ValidationAnnoPatternWithFlags                         -- KW["pattern"] KW["("] _1 KW[","] _2 KW[")"],
   ValidationAnnoPatternWithFlags.2:iter-star             -- _1,
   FlagCanonEq                                            -- KW["canonicalequivalence"],
   FlagCaseInsensitive                                    -- KW["caseinsensitive"],
   FlagComments                                           -- KW["comments"],
   FlagDotAll                                             -- KW["dotall"],
   FlagLiteral                                            -- KW["literal"],
   FlagMultiline                                          -- KW["multiline"],
   FlagUnicodeCase                                        -- KW["unicodecase"],
   FlagUnixLines                                          -- KW["unixlines"],
   ValidationAnnoMax                                      -- KW["max"] KW["("] _1 KW[")"],
   ValidationAnnoMin                                      -- KW["min"] KW["("] _1 KW[")"],
   ValidationAnnoRange                                    -- KW["range"] KW["("] _1 KW[","] _2 KW[")"],
   ValidationAnnoMinRange                                 -- KW["minrange"] KW["("] _1 KW[")"],
   ValidationAnnoMaxRange                                 -- KW["maxrange"] KW["("] _1 KW[")"],
   ValidationAnnoDigits                                   -- KW["digits"] KW["("] _1 KW[","] _2 KW[")"],
   ValidationAnnoPast                                     -- KW["past"],
   ValidationAnnoFuture                                   -- KW["future"],
   ValidationAnnoSize                                     -- KW["size"] KW["("] _1 KW[","] _2 KW[")"],
   ValidationAnnoMinSize                                  -- KW["minsize"] KW["("] _1 KW[")"],
   ValidationAnnoMaxSize                                  -- KW["maxsize"] KW["("] _1 KW[")"],
   ValidationAnnoNotNull                                  -- KW["notnull"],
   ValidationAnnoAssertTrue                               -- KW["asserttrue"],
   ValidationAnnoAssertFalse                              -- KW["assertfalse"],
   ValidationAnnoValid                                    -- KW["valid"],
   Procedure                                              -- KW["procedure"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Procedure.3:iter-star                                  -- _1,
   AutoProcedure                                          -- KW["auto"] KW["procedure"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   AutoProcedure.3:iter-star                              -- _1,
   ExtendProcedure                                        -- KW["extend"] KW["procedure"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   ExtendProcedure.3:iter-star                            -- _1,
   ProcedureWho                                           -- KW["who"] KW["{"] _1 KW["}"],
   ProcedureWhen                                          -- KW["when"] KW["{"] _1 KW["}"],
   ProcedureDo                                            -- KW["do"] _1,
   ProcedureDone                                          -- KW["done"] _1,
   ProcedureEnabled                                       -- KW["enabled"] _1,
   ProcedureDisabled                                      -- KW["disabled"] _1,
   ProcedureView                                          -- KW["view"] KW["{"] _1 KW["}"],
   ProcedureView.1:iter-star                              -- _1,
   ProcedureProcess                                       -- KW["process"] KW["{"] _1 KW["}"],
   ProcedureProcessed                                     -- KW["processed"] _1,
   ProcCall                                               -- _1 KW["("] _2 KW[")"],
   ProcSeq                                                -- _1 KW[";"] _2,
   ProcWhile                                              -- KW["while"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   ProcRepeatUntil                                        -- KW["repeat"] KW["{"] _1 KW["}"] KW["until"] _2,
   ProcIfNoElse                                           -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   ProcIf                                                 -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"] KW["else"] KW["{"] _3 KW["}"],
   ProcXor                                                -- _1 KW["xor"] _2,
   ProcAnd                                                -- _1 KW["and"] _2,
   ProcPlus                                               -- _1 KW["+"] _2,
   Derive                                                 -- KW["derive"] _1 KW["from"] _2 KW["for"] KW["("] _3 KW[")"],
   Derive.3:iter-star-sep                                 -- _1 KW[","],
   Derive                                                 -- KW["derive"] _1 KW["from"] _2,
   Derive                                                 -- KW["derive"] _1 KW["from"] _2 KW["for"] KW["("] _3 KW[")"] _4,
   Derive.3:iter-star-sep                                 -- _1 KW[","],
   Derive                                                 -- KW["derive"] _1 KW["from"] _2 _3,
   Derive                                                 -- KW["derive"] _1 _2,
   DeriveDefault                                          -- _1,
   DeriveMode                                             -- _1 KW["("] _2 KW[")"],
   DeriveBody                                             -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   DeriveBody.1:iter-star                                 -- _1,
   DeriveBodyElement                                      -- _1 KW["{"] _2 KW["}"],
   DeriveBodyElement.2:iter-star                          -- _1,
   DeriveCrud                                             -- KW["derive"] KW["crud"] _1,
   DeriveCrud                                             -- KW["derive"] KW["CRUD"] _1,
   PagedForAll                                            -- KW["for"] KW["("] _1 KW[":"] _2 _3 KW["per"] _4 KW[")"] KW["{"] _5 KW["}"],
   PagedForAll.5:iter-star                                -- _1,
   PagedForAllNoFilter                                    -- KW["for"] KW["("] _1 KW[":"] _2 KW["per"] _3 KW[")"] KW["{"] _4 KW["}"],
   PagedForAllNoFilter.4:iter-star                        -- _1,
   PagedFor                                               -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 _4 KW["per"] _5 KW[")"] KW["{"] _6 KW["}"],
   PagedFor.6:iter-star                                   -- _1,
   PagedForNoFilter                                       -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW["per"] _4 KW[")"] KW["{"] _5 KW["}"],
   PagedForNoFilter.5:iter-star                           -- _1,
   ThemeDefinition                                        -- KW["theme"] _1 _2 KW["("] KW[")"] KW["{"] _3 KW["}"],
   ThemeDefinition.3:iter-star                            -- _1,
   StyleSection                                           -- KW["style"] _1 _2,
   StyleSection.2:iter-star                               -- _1,
   StyleDefinition                                        -- _1 KW["{"] _2 KW["}"],
   StyleDefinition.2:iter-star                            -- _1,
   Selector                                               -- _1 _2,
   Selector.2:iter-star                                   -- _1,
   Selector.2:iter-star.1:seq                             -- _1 _2 _3,
   Selector.2:iter-star.1:seq.3:opt                       -- _1,
   SimpleSelector                                         -- _1 _2,
   IdSimpleSelector                                       -- KW["#"] _1,
   ElemSimpleSelector                                     -- _1,
   ElemSimpleAttrSelector                                 -- _1 _2,
   ElemSimpleAttrSelector.2:iter                          -- _1,
   ElemClassAttrSelector                                  -- _1 KW["."] _2 _3,
   ElemClassAttrSelector.3:iter                           -- _1,
   ClassSimpleSelector                                    -- KW["."] _1,
   SimpleSelector                                         -- _1,
   UniversalSimpleSelector                                -- KW["*"],
   SelectorAttribute                                      -- KW[":"] _1,
   ChildCombinator                                        -- KW[">"],
   DescendantCombinator                                   -- KW[">>"],
   MatchDefinition                                        -- _1 KW["("] _2 KW[")"],
   StyleVarDecl                                           -- KW["const"] _1 KW[":"] _2 KW[";"],
   StyleVarDeclInit                                       -- KW["const"] _1 KW[":"] _2 KW[":="] _3 KW[";"],
   StyleDeclaration                                       -- _1 KW[":="] _2 KW[";"],
   StyleProperty                                          -- _1,
   StylePropertyValue                                     -- _1 KW["."] _2,
   StyleVar                                               -- _1,
   StyleValueExpression                                   -- KW["("] _1 KW[")"] KW["."] _2,
   StyleAdd                                               -- _1 KW["+"] _2,
   StyleSub                                               -- _1 KW["-"] _2,
   StyleMul                                               -- _1 KW["*"] _2,
   StyleDiv                                               -- _1 KW["/"] _2,
   StyleValue                                             -- _1 _2,
   StyleValue                                             -- _1,
   StyleValue                                             -- _1 _2,
   StyleValue.2:iter                                      -- _1,
   StyleValue                                             -- _1,
   StyleValue                                             -- _1,
   StyleValue                                             -- _1,
   StyleValue                                             -- _1,
   StyleValueExtension                                    -- KW["."] _1,
   StyleSort                                              -- _1 _2,
   StyleSort                                              -- _1,
   Uri                                                    -- KW["url"] KW["("] _1 KW[")"],
   Hash                                                   -- KW["#"] _1,
   LayoutSection                                          -- V  [H  [KW["layout"]] _1],
   LayoutSection.1:iter-star                              -- _1,
   LayoutDefinition                                       -- _1 _2 KW["{"] _3 KW["}"],
   LayoutDefinition.3:iter-star                           -- _1,
   LayoutDefinition                                       -- _1 KW["{"] _2 KW["}"],
   LayoutDefinition.2:iter-star                           -- _1,
   FloatStatement                                         -- KW["float"] KW["{"] _1 KW["}"] KW[";"],
   FloatStatement.1:iter-star                             -- _1,
   LayoutStatement                                        -- _1 KW[";"],
   NamedLayoutExpression                                  -- _1 KW[":"] KW["["] _2 KW["]"],
   LayoutExpression                                       -- _1,
   LayoutExpression                                       -- _1,
   Enum                                                   -- KW["enum"] _1 KW["{"] _2 KW["}"],
   Enum.2:iter-star-sep                                   -- _1 KW[","],
   EnumValue                                              -- _1 KW["("] _2 KW[")"],
   Call                                                   -- _1 KW["."] _2 KW["("] _3 KW[")"],
   Call.3:iter-star-sep                                   -- _1 KW[","],
   RegexPattern                                           -- KW["/"] _1 KW["/"],
   SingleBranch                                           -- _1,
   TupleBranch                                            -- _1 KW["|"] _2,
   Pieces                                                 -- _1,
   Pieces.1:iter                                          -- _1,
   SingleAtom                                             -- _1,
   QuantifiedAtom                                         -- _1 _2,
   GreedyExactBound                                       -- KW["{"] _1 KW["}"],
   GreedyLowerBound                                       -- KW["{"] _1 KW[","] KW["}"],
   GreedyLowerUpperBound                                  -- KW["{"] _1 KW[","] _2 KW["}"],
   GreedyOnceOrNot                                        -- KW["?"],
   GreedyZeroOrMore                                       -- KW["*"],
   GreedyOneOrMore                                        -- KW["+"],
   ReluctantExactBound                                    -- KW["{"] _1 KW["}?"],
   ReluctantLowerBound                                    -- KW["{"] _1 KW[","] KW["}?"],
   ReluctantLowerUpperBound                               -- KW["{"] _1 KW[","] _2 KW["}?"],
   ReluctantOnceOrNot                                     -- KW["??"],
   ReluctantZeroOrMore                                    -- KW["*?"],
   ReluctantOneOrMore                                     -- KW["+?"],
   PossessiveExactBound                                   -- KW["{"] _1 KW["}+"],
   PossessiveLowerBound                                   -- KW["{"] _1 KW[","] KW["}+"],
   PossessiveLowerUpperBound                              -- KW["{"] _1 KW[","] _2 KW["}+"],
   PossessiveOnceOrNot                                    -- KW["?+"],
   PossessiveZeroOrMore                                   -- KW["*+"],
   PossessiveOneOrMore                                    -- KW["++"],
   Capture                                                -- KW["("] _1 KW[")"],
   NonCapture                                             -- KW["(?:"] _1 KW[")"],
   PositiveLookahead                                      -- KW["(?="] _1 KW[")"],
   NegativeLookahead                                      -- KW["(?!"] _1 KW[")"],
   PositiveLookbehind                                     -- KW["(?<="] _1 KW[")"],
   NegativeLookbehind                                     -- KW["(?<!"] _1 KW[")"],
   PythonCapture                                          -- KW["(?P<"] _1 KW[">"] _2 KW[")"],
   RegexCapture                                           -- KW["("] _1 KW[")@{"] _2 KW["}"],
   Empty                                                  -- KW["()"],
   SingleCharacter                                        -- KW["."],
   LineStart                                              -- KW["^"],
   LineEnd                                                -- KW["$"],
   CharacterClass                                         -- _1,
   AtomLiteral                                            -- _1,
   AtomCharacter                                          -- _1,
   QuotedAtom                                             -- KW["\\Q"] _1 KW["\\E"],
   BracketList                                            -- V  [V vs=2 [KW["["] _1] KW["]"]],
   BracketList.1:iter                                     -- _1,
   NegatedBracketList                                     -- V  [V vs=2 [KW["[^"] _1] KW["]"]],
   NegatedBracketList.1:iter                              -- _1,
   Range                                                  -- _1 KW["-"] _2,
   Range.1:alt                                            -- _1 _2,
   Range.2:alt                                            -- _1 _2,
   Union                                                  -- _1,
   BracketLiteral                                         -- _1,
   BracketCharacter                                       -- _1,
   LowerClass                                             -- KW["Lower"],
   UpperClass                                             -- KW["Upper"],
   ASCIIClass                                             -- KW["ASCII"],
   AlphaClass                                             -- KW["Alpha"],
   DigitClass                                             -- KW["Digit"],
   AlnumClass                                             -- KW["Alnum"],
   PunctClass                                             -- KW["Punct"],
   GraphClass                                             -- KW["Graph"],
   PrintClass                                             -- KW["Print"],
   BlankClass                                             -- KW["Blank"],
   CntrlClass                                             -- KW["Cntrl"],
   XDigitClass                                            -- KW["XDigit"],
   WhiteSpace                                             -- KW["Space"],
   JavaIsLowerCase                                        -- KW["javaLowerCase"],
   JavaIsLowerCase                                        -- KW["javaUpperCase"],
   JavaIsWhitespace                                       -- KW["javaWhitespace"],
   JavaIsMirrored                                         -- KW["javaMirrored"],
   GreekBlock                                             -- KW["InGreek"],
   UppercaseLetter                                        -- KW["Lu"],
   CurrencySymbol                                         -- KW["Sc"],
   DoubleQuote                                            -- KW["\""],
   DoubleQuote                                            -- KW["\""],
   OctalChar                                              -- KW["\\0"] _1,
   HexHexChar                                             -- KW["\\x"] _1,
   DecHexChar                                             -- KW["\\u"] _1,
   Tab                                                    -- KW["\\t"],
   Newline                                                -- KW["\\n"],
   Return                                                 -- KW["\\r"],
   Formfeed                                               -- KW["\\f"],
   Alarm                                                  -- KW["\\a"],
   Escape                                                 -- KW["\\e"],
   WordChar                                               -- KW["\\w"],
   NonWordChar                                            -- KW["\\W"],
   WhiteSpaceChar                                         -- KW["\\s"],
   NonWhiteSpaceChar                                      -- KW["\\S"],
   DigitChar                                              -- KW["\\d"],
   NonDigitChar                                           -- KW["\\D"],
   ControlCharacter                                       -- KW["\\c"] _1,
   WordBoundry                                            -- KW["\\b"],
   NonWordBoundry                                         -- KW["\\B"],
   InputBeginBoundry                                      -- KW["\\A"],
   PrevMatchEndBoundry                                    -- KW["\\G"],
   EndInputBoundry                                        -- KW["\\Z"],
   EndInputFinalBoundry                                   -- KW["\\z"],
   BackReference                                          -- KW["\\"] _1,
   Space                                                  -- KW["\\ "],
   Tab                                                    -- KW["\\\t"],
   Newline                                                -- KW["\\\n"],
   OctalChar                                              -- KW["\\0"] _1,
   HexHexChar                                             -- KW["\\x"] _1,
   DecHexChar                                             -- KW["\\u"] _1,
   Tab                                                    -- KW["\\t"],
   Newline                                                -- KW["\\n"],
   Return                                                 -- KW["\\r"],
   Formfeed                                               -- KW["\\f"],
   Alarm                                                  -- KW["\\a"],
   Escape                                                 -- KW["\\e"],
   WordChar                                               -- KW["\\w"],
   NonWordChar                                            -- KW["\\W"],
   WhiteSpaceChar                                         -- KW["\\s"],
   NonWhiteSpaceChar                                      -- KW["\\S"],
   DigitChar                                              -- KW["\\d"],
   NonDigitChar                                           -- KW["\\D"],
   ControlCharacter                                       -- KW["\\c"] _1,
   WordBoundry                                            -- KW["\\b"],
   NonWordBoundry                                         -- KW["\\B"],
   InputBeginBoundry                                      -- KW["\\A"],
   PrevMatchEndBoundry                                    -- KW["\\G"],
   EndInputBoundry                                        -- KW["\\Z"],
   EndInputFinalBoundry                                   -- KW["\\z"],
   BackReference                                          -- KW["\\"] _1,
   Space                                                  -- KW["\\ "],
   Tab                                                    -- KW["\\\t"],
   Newline                                                -- KW["\\\n"],
   Quoted                                                 -- KW["\\"] _1,
   Quoted                                                 -- KW["\\"] _1,
   DoubleQuote                                            -- KW["\""],
   DoubleQuote                                            -- KW["\""],
   RegexId                                                -- _1,
   JSElement                                              -- KW["<"] KW["script"] _1 KW[">"] _2 KW["</"] KW["script"] KW[">"],
   JSElement.1:iter-star                                  -- _1,
   JSElement.2:iter-star                                  -- _1,
   JSString                                               -- _1,
   JSExp                                                  -- KW["~"] _1,
   JSTilde                                                -- KW["\\~"],
   XMLEmptyElement                                        -- KW["<"] _1 _2 KW["/>"],
   XMLEmptyElement.2:iter-star                            -- _1,
   XMLElement                                             -- KW["<"] _1 _2 KW[">"] _3 KW["</"] _4 KW[">"],
   XMLElement.2:iter-star                                 -- _1,
   XMLElement.3:iter-star                                 -- _1,
   XMLAttributesIf                                        -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   XMLAttributesIf.2:iter-star                            -- _1,
   XMLAttributesIfElse                                    -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"] KW["else"] KW["{"] _3 KW["}"],
   XMLAttributesIfElse.2:iter-star                        -- _1,
   XMLAttributesIfElse.3:iter-star                        -- _1,
   Attribute                                              -- _1 KW["="] _2,
   AllAttributes                                          -- KW["all attributes"],
   AllAttributeExceptExp                                  -- KW["all attributes except"] _1,
   AttributesExp                                          -- KW["attributes"] _1,
   AccessControlDefinition                                -- KW["access"] KW["control"] KW["rules"] _1 _2,
   AccessControlDefinition.1:opt                          -- _1,
   AccessControlDefinition.2:iter-star                    -- _1,
   AccessControlDefinition                                -- KW["access"] KW["control"] KW["rules"] KW["{"] _1 _2 KW["}"],
   AccessControlDefinition.1:opt                          -- _1,
   AccessControlDefinition.2:iter-star                    -- _1,
   AccessControlPrincipal                                 -- KW["principal"] KW["is"] _1 KW["with"] KW["credentials"] _2,
   AccessControlPrincipal.2:iter-sep                      -- _1 KW[","],
   AccessControlPrincipal                                 -- KW["principal"] KW["is"] _1 KW["with"] KW["credentials"] _2,
   AccessControlPrincipal.2:iter-sep                      -- _1 KW[","],
   AccessControlRule                                      -- KW["rule"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 _5 KW["}"],
   AccessControlRule.5:iter-star                          -- _1,
   AccessControlRule                                      -- KW["rules"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 _5 KW["}"],
   AccessControlRule.5:iter-star                          -- _1,
   MatchArgs                                              -- _1 _2,
   MatchArgs.1:iter-star-sep                              -- _1 KW[","],
   MatchArgs.2:opt                                        -- _1,
   MatchArgs                                              -- _1 _2,
   MatchArgs.1:iter-star-sep                              -- _1 KW[","],
   MatchArgs.2:opt                                        -- _1,
   SpecialAccessControlRule                               -- KW["rule"] _1 KW["{"] _2 KW["}"],
   Predicate                                              -- KW["predicate"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Predicate.2:iter-star-sep                              -- _1 KW[","],
   Predicate                                              -- KW["predicate"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Predicate.2:iter-star-sep                              -- _1 KW[","],
   PredicateInEntity                                      -- KW["predicate"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   PredicateInEntity.2:iter-star-sep                      -- _1 KW[","],
   AccessControlPointcutElement                           -- _1 _2 KW["("] _3 _4 KW[")"],
   AccessControlPointcutElement.3:iter-star-sep           -- _1 KW[","],
   AccessControlPointcutElement.4:opt                     -- _1,
   AccessControlPointcut                                  -- KW["pointcut"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   AccessControlPointcut.2:iter-star-sep                  -- _1 KW[","],
   AccessControlPointcut.3:iter-star-sep                  -- _1 KW[","],
   AccessControlImportRules                               -- KW["apply ac rules"] _1 KW["("] _2 KW[")"],
   AccessControlImportRules.2:iter-star-sep               -- _1 KW[","],
   Var                                                    -- _1,
   ACPolicy                                               -- KW["access"] KW["control"] KW["policy"] _1,
   Name                                                   -- _1,
   PolicyAnd                                              -- _1 KW["AND"] _2,
   PolicyOr                                               -- _1 KW["OR"] _2,
   IgnoreAccessControl                                    -- KW["ignore-access-control"],
   ValidateCreateAnno                                     -- KW["validatecreate"] KW["("] _1 KW[","] _2 KW[")"],
   ValidateUpdateAnno                                     -- KW["validateupdate"] KW["("] _1 KW[","] _2 KW[")"],
   ValidateDeleteAnno                                     -- KW["validatedelete"] KW["("] _1 KW[","] _2 KW[")"],
   ValidateAnno                                           -- KW["validate"] KW["("] _1 KW[","] _2 KW[")"],
   NamedValidateAnno                                      -- _1 KW[":"] KW["validate"] KW["("] _2 KW[","] _3 KW[")"],
   ValidateEntity                                         -- KW["validate"] KW["("] _1 KW[","] _2 KW[")"],
   ValidateStatement                                      -- KW["validate"] KW["("] _1 KW[","] _2 KW[")"] KW[";"],
   NamedValidateStatement                                 -- _1 KW[":"] KW["validate"] KW["("] _2 KW[","] _3 KW[")"] KW[";"],
   ValidationErrors                                       -- KW["validationErrors"] KW["("] _1 KW[")"],
   ValidationErrors                                       -- KW["validationErrors"] KW["("] KW[")"],
   ValidationContext                                      -- KW["validationContext"] KW["{"] _1 KW["}"],
   ValidationContext.1:iter-star                          -- _1,
   GlobalsDefinition                                      -- KW["globals"] KW["{"] _1 KW["}"],
   GlobalsDefinition.1:iter-star                          -- _1,
   Entity                                                 -- KW["entity"] _1 KW[":"] _2 KW["{"] _3 KW["}"],
   Entity.3:iter-star                                     -- _1,
   EntityNoSuper                                          -- KW["entity"] _1 KW["{"] _2 KW["}"],
   EntityNoSuper.2:iter-star                              -- _1,
   SessionEntity                                          -- KW["session"] _1 KW["{"] _2 KW["}"],
   SessionEntity.2:iter-star                              -- _1,
   CachedEntity                                           -- KW["cache"],
   ExtendEntity                                           -- KW["extend"] KW["entity"] _1 KW["{"] _2 KW["}"],
   ExtendEntity.2:iter-star                               -- _1,
   ExtendSessionEntity                                    -- KW["extend"] KW["session"] _1 KW["{"] _2 KW["}"],
   ExtendSessionEntity.2:iter-star                        -- _1,
   RequestScope                                           -- KW["request"] _1,
   Property                                               -- _1 _2 _3 KW["("] _4 KW[")"],
   Property.4:iter-star-sep                               -- _1 KW[","],
   PropertyNoAnno                                         -- _1 _2 _3,
   DerivedProperty                                        -- _1 _2 _3 KW["("] _4 KW[")"] KW[":="] _5,
   DerivedProperty.4:iter-star-sep                        -- _1 KW[","],
   DerivedPropertyNoAnno                                  -- _1 _2 _3 KW[":="] _4,
   Simple                                                 -- KW["::"],
   Ref                                                    -- KW["->"],
   Comp                                                   -- KW["<>"],
   FunctionSort                                           -- KW["function"] _1 _2,
   UnnamedArg                                             -- _1,
   Arg                                                    -- _1 KW[":"] _2,
   Arg                                                    -- _1 KW[":"] _2,
   SimpleAnno                                             -- _1,
   InverseAnno                                            -- KW["inverse"] KW["="] _1 KW["."] _2,
   IncompleteInverseAnno                                  -- KW["inverse"] KW["="] _1,
   InverseSlaveAnno                                       -- KW["inverseSlave"] KW["="] _1 KW["."] _2,
   InlineAnno                                             -- KW["inline"] KW["("] _1 KW[")"],
   InlineAnno.1:iter-star-sep                             -- _1 KW[","],
   SelectAnno                                             -- KW["select"] KW["="] _1,
   NotNullAnno                                            -- KW["not null"],
   NotEmptyAnno                                           -- KW["not empty"],
   AllowedAnno                                            -- KW["allowed"] KW["="] _1,
   DefaultAnno                                            -- KW["default"] KW["="] _1,
   LengthAnno                                             -- KW["length"] KW["="] _1,
   FormatAnno                                             -- KW["format"] KW["="] _1,
   IndexAnno                                              -- KW["index"] KW["("] KW[")"],
   IndexAnno                                              -- KW["index"] KW["("] _1 KW[")"],
   CollationAnno                                          -- KW["collation"] KW["("] _1 KW[")"],
   IdErrorAnno                                            -- KW["iderror"] KW["="] _1,
   IdEmptyErrorAnno                                       -- KW["idemptyerror"] KW["="] _1,
   DeleteStatement                                        -- KW["delete"] _1 _2,
   DeleteStatement.2:opt                                  -- _1,
   QueryUnion                                             -- _1 KW["union"] _2,
   QueryRule                                              -- _1 _2 _3 _4,
   QueryRule.2:opt                                        -- _1,
   QueryRule.3:opt                                        -- _1,
   QueryRule.4:opt                                        -- _1,
   SelectFrom                                             -- _1 _2,
   SelectFrom.1:opt                                       -- _1,
   Select                                                 -- KW["select"] _1 _2,
   Select.1:opt                                           -- _1,
   Distinct                                               -- KW["distinct"],
   NewExpression                                          -- KW["new"] _1 KW["("] _2 KW[")"],
   SelectObject                                           -- KW["object"] KW["("] _1 KW[")"],
   FromClause                                             -- V  [H  [KW["from"]] _1],
   FromClause.1:iter-sep                                  -- _1 KW[","],
   FromRangeJoin                                          -- _1 _2,
   FromRangeJoin.2:iter-star                              -- _1,
   LeftJoin                                               -- KW["left"],
   RightJoin                                              -- KW["right"],
   LeftOuterJoin                                          -- KW["left"] KW["outer"],
   RightOuterJoin                                         -- KW["right"] KW["outer"],
   FullJoin                                               -- KW["full"],
   InnerJoin                                              -- KW["inner"],
   FromJoin                                               -- _1 KW["join"] _2 _3 _4 _5 _6,
   FromJoin.1:opt                                         -- _1,
   FromJoin.2:opt                                         -- _1,
   FromJoin.4:opt                                         -- _1,
   FromJoin.5:opt                                         -- _1,
   FromJoin.6:opt                                         -- _1,
   Fetch                                                  -- KW["fetch"],
   WithClause                                             -- KW["with"] _1,
   FromClass                                              -- _1 _2 _3,
   FromClass.2:opt                                        -- _1,
   FromClass.3:opt                                        -- _1,
   InClassDeclaration                                     -- _1 KW["in"] KW["class"] _2,
   InCollection                                           -- KW["in"] KW["("] _1 KW[")"] _2,
   InCollectionElements                                   -- _1 KW["in"] KW["elements"] KW["("] _2 KW[")"],
   AsAlias                                                -- KW["as"] _1,
   Alias                                                  -- _1,
   PropertyFetch                                          -- KW["fetch"] KW["all"] KW["properties"],
   GroupBy                                                -- KW["group"] KW["by"] _1 _2,
   GroupBy.1:iter-sep                                     -- _1 KW[","],
   GroupBy.2:opt                                          -- _1,
   OrderByClause                                          -- V  [H  [KW["order"] KW["by"]] _1],
   OrderByClause.1:iter-sep                               -- _1 KW[","],
   OrderElement                                           -- _1 _2,
   OrderElement.2:opt                                     -- _1,
   Ascending                                              -- KW["asc"],
   Ascending                                              -- KW["ascending"],
   Descending                                             -- KW["desc"],
   Descending                                             -- KW["descending"],
   HavingClause                                           -- KW["having"] _1,
   WhereClause                                            -- KW["where"] _1,
   SelectedPropertiesList                                 -- _1,
   SelectedPropertiesList.1:iter-sep                      -- _1 KW[","],
   QuotedAliasedExpression                                -- KW["'"] _1 _2 KW["'"],
   QuotedAliasedExpression.2:opt                          -- _1,
   AliasedExpression                                      -- _1 _2,
   AliasedExpression.2:opt                                -- _1,
   QueryOr                                                -- _1 KW["or"] _2,
   QueryAnd                                               -- _1 KW["and"] _2,
   QueryNot                                               -- KW["not"] _1,
   EQ                                                     -- _1 KW["="] _2,
   IS                                                     -- _1 KW["is"] _2,
   NE                                                     -- _1 KW["!="] _2,
   SQLNE                                                  -- _1 KW["<>"] _2,
   LIKE                                                   -- _1 KW["like"] _2,
   NOTLIKE                                                -- _1 KW["not"] KW["like"] _2,
   LT                                                     -- _1 KW["<"] _2,
   LE                                                     -- _1 KW["<="] _2,
   GT                                                     -- _1 KW[">"] _2,
   GE                                                     -- _1 KW[">="] _2,
   In                                                     -- _1 KW["in"] _2,
   NotIn                                                  -- _1 KW["not"] KW["in"] _2,
   MemberOf                                               -- _1 KW["member"] KW["of"] _2,
   NotMemberOf                                            -- _1 KW["not"] KW["member"] KW["of"] _2,
   Concat                                                 -- _1 KW["||"] _2,
   Plus                                                   -- _1 KW["+"] _2,
   Minus                                                  -- _1 KW["-"] _2,
   Multiply                                               -- _1 KW["*"] _2,
   Divide                                                 -- _1 KW["/"] _2,
   Modulo                                                 -- _1 KW["%"] _2,
   UMinus                                                 -- KW["-"] _1,
   HQLFunCurDate                                          -- KW["current_date"] KW["("] KW[")"],
   HQLFunCurTime                                          -- KW["current_time"] KW["("] KW[")"],
   HQLFunCurTimestamp                                     -- KW["current_timestamp"] KW["("] KW[")"],
   HQLFunSecond                                           -- KW["second"] KW["("] _1 KW[")"],
   HQLFunMinute                                           -- KW["minute"] KW["("] _1 KW[")"],
   HQLFunHour                                             -- KW["hour"] KW["("] _1 KW[")"],
   HQLFunDay                                              -- KW["day"] KW["("] _1 KW[")"],
   HQLFunMonth                                            -- KW["month"] KW["("] _1 KW[")"],
   HQLFunYear                                             -- KW["year"] KW["("] _1 KW[")"],
   IdParam                                                -- _1,
   NumParam                                               -- _1,
   Avg                                                    -- KW["avg"] KW["("] _1 KW[")"],
   Sum                                                    -- KW["sum"] KW["("] _1 KW[")"],
   Min                                                    -- KW["min"] KW["("] _1 KW[")"],
   Max                                                    -- KW["max"] KW["("] _1 KW[")"],
   CountStar                                              -- KW["count"] KW["("] KW["*"] KW[")"],
   Count                                                  -- KW["count"] KW["("] _1 KW[")"],
   Elements                                               -- KW["elements"] KW["("] _1 KW[")"],
   Indices                                                -- KW["indices"] KW["("] _1 KW[")"],
   Paren                                                  -- KW["("] _1 KW[")"],
   Paren.1:iter-sep                                       -- _1 KW[","],
   Paren                                                  -- KW["("] _1 KW[")"],
   True                                                   -- KW["true"],
   False                                                  -- KW["false"],
   Empty                                                  -- KW["empty"],
   Null                                                   -- KW["null"],
   Path                                                   -- _1,
   Path.1:iter-sep                                        -- _1 KW["."],
   String                                                 -- _1,
   Function                                               -- KW["function"] _1 KW["("] _2 KW[")"] _3 _4,
   Function.2:iter-star-sep                               -- _1 KW[","],
   ExtendFunction                                         -- KW["extend"] _1,
   StaticEntityFunction                                   -- KW["static"] KW["function"] _1 KW["("] _2 KW[")"] _3 _4,
   StaticEntityFunction.2:iter-star-sep                   -- _1 KW[","],
   ReturnType                                             -- KW[":"] _1,
   FunctionExp                                            -- KW["function"] _1 _2 _3,
   FunctionRef                                            -- KW["function."] _1 KW["("] _2 KW[")"] _3,
   FunctionRef.2:iter-star-sep                            -- _1 KW[","],
   FunctionRefCall                                        -- _1 KW["("] _2 KW[")"],
   FunctionRefCall.2:iter-star-sep                        -- _1 KW[","],
   FunctionRefCallPartial                                 -- _1 KW["("] KW["*"] KW[","] _2 KW[")"],
   FunctionRefCallPartial.2:iter-star-sep                 -- _1 KW[","],
   Block                                                  -- KW["{"] _1 KW["}"],
   Stat                                                   -- _1 KW[";"],
   Return                                                 -- KW["return"] _1 KW[";"],
   ReturnEmpty                                            -- KW["return"] KW[";"],
   GoTo                                                   -- KW["goto"] _1 KW[";"],
   GoTo                                                   -- KW["goto"] KW["("] _1 KW[")"] KW[";"],
   Schedule                                               -- KW["schedule"] _1 KW["for"] _2 KW[";"],
   ScheduleNoFor                                          -- KW["schedule"] _1 KW[";"],
   VarDecl                                                -- KW["var"] _1 KW[":"] _2 KW[";"],
   VarDecl                                                -- KW["var"] _1 KW[":"] _2,
   VarDeclInit                                            -- KW["var"] _1 KW[":"] _2 KW[":="] _3 KW[";"],
   VarDeclInitInferred                                    -- KW["var"] _1 KW[":="] _2 KW[";"],
   VarDeclInit                                            -- KW["var"] _1 KW[":"] _2 KW[":="] _3,
   VarDeclInitInferred                                    -- KW["var"] _1 KW[":="] _2,
   If                                                     -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   IfNoElse                                               -- KW["if"] KW["("] _1 KW[")"] _2,
   Case                                                   -- KW["case"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   Case.2:iter-star                                       -- _1,
   CaseAlt                                                -- _1 _2,
   CaseDefault                                            -- KW["default"] _1,
   IfExp                                                  -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   ForStmt                                                -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 _4 KW[")"] _5,
   ForStmtNoFilter                                        -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] _4,
   ForAllStmt                                             -- KW["for"] KW["("] _1 KW[":"] _2 _3 KW[")"] _4,
   ForAllStmtNoFilter                                     -- KW["for"] KW["("] _1 KW[":"] _2 KW[")"] _3,
   ForCountStmt                                           -- KW["for"] KW["("] _1 KW[":"] KW["Int"] KW["from"] _2 KW["to"] _3 KW[")"] _4,
   WhileStmt                                              -- KW["while"] KW["("] _1 KW[")"] _2,
   Int                                                    -- _1,
   Long                                                   -- _1,
   Float                                                  -- _1,
   String                                                 -- _1,
   Var                                                    -- _1,
   ExternalScopeVar                                       -- KW["externalscope"] KW["."] _1,
   GlobalVar                                              -- KW["global"] KW["."] _1,
   FieldAccess                                            -- _1 KW["."] _2,
   CollectionIndex                                        -- _1 KW["["] _2 KW["]"],
   ObjectCreation                                         -- _1 KW["{"] _2 KW["}"],
   ObjectCreation.2:iter-star                             -- _1,
   ObjectCreation                                         -- _1 KW["{"] _2 KW["}"],
   ObjectCreation.2:iter-star-sep                         -- _1 KW[","],
   ObjectPropertyAssignment                               -- _1 KW[":="] _2,
   IncompleteObjectPropertyAssignment                     -- _1,
   Assignment                                             -- _1 KW[":="] _2,
   MapCreation                                            -- V  [V vs=2 [KW["["] _1] KW["]"]],
   MapCreation.1:iter-star                                -- _1,
   Mapping                                                -- _1 KW["->"] _2,
   ListCreation                                           -- KW["["] _1 KW["]"],
   ListCreation.1:iter-star-sep                           -- _1 KW[","],
   SetCreation                                            -- KW["{"] _1 KW["}"],
   SetCreation.1:iter-star-sep                            -- _1 KW[","],
   TypedListCreation                                      -- KW["List"] KW["<"] _1 KW[">"] KW["("] _2 KW[")"],
   TypedListCreation.2:iter-star-sep                      -- _1 KW[","],
   TypedSetCreation                                       -- KW["Set"] KW["<"] _1 KW[">"] KW["("] _2 KW[")"],
   TypedSetCreation.2:iter-star-sep                       -- _1 KW[","],
   ThisCall                                               -- _1 KW["("] _2 KW[")"],
   ThisCall.2:iter-star-sep                               -- _1 KW[","],
   Call                                                   -- _1 KW["."] _2 KW["("] _3 KW[")"],
   Call.3:iter-star-sep                                   -- _1 KW[","],
   IsA                                                    -- _1 KW["is"] KW["a"] _2,
   Cast                                                   -- _1 KW["as"] _2,
   InColl                                                 -- _1 KW["in"] _2,
   Eq                                                     -- _1 KW["=="] _2,
   NotEq                                                  -- _1 KW["!="] _2,
   LargerThan                                             -- _1 KW[">"] _2,
   LargerThanOrEqual                                      -- _1 KW[">="] _2,
   SmallerThan                                            -- _1 KW["<"] _2,
   SmallerThanOrEqual                                     -- _1 KW["<="] _2,
   True                                                   -- KW["true"],
   False                                                  -- KW["false"],
   Null                                                   -- KW["null"],
   And                                                    -- _1 KW["&&"] _2,
   Or                                                     -- _1 KW["||"] _2,
   Not                                                    -- KW["!"] _1,
   ForExp                                                 -- KW["["] _1 KW["for"] KW["("] _2 KW[":"] _3 KW["in"] _4 _5 KW[")"] KW["]"],
   ForExpNoFilter                                         -- KW["["] _1 KW["for"] KW["("] _2 KW[":"] _3 KW["in"] _4 KW[")"] KW["]"],
   ForExp                                                 -- KW["["] _1 KW["|"] _2 KW[":"] _3 KW["in"] _4 _5 KW["]"],
   ForExpNoFilter                                         -- KW["["] _1 KW["|"] _2 KW[":"] _3 KW["in"] _4 KW["]"],
   AndForExp                                              -- KW["And"] _1,
   OrForExp                                               -- KW["Or"] _1,
   Mul                                                    -- _1 KW["*"] _2,
   Div                                                    -- _1 KW["/"] _2,
   Mod                                                    -- _1 KW["%"] _2,
   Add                                                    -- _1 KW["+"] _2,
   Sub                                                    -- _1 KW["-"] _2,
   HqlQuery                                               -- _1,
   HqlQuery.1:parameterized-sort                          -- _1 _2,
   HqlQuery.1:parameterized-sort.1:"QueryRule"            -- ,
   HqlQueryLimit                                          -- _1 KW["limit"] _2,
   HqlQueryLimit.1:parameterized-sort                     -- _1 _2,
   HqlQueryLimit.1:parameterized-sort.1:"QueryRule"       -- ,
   HqlQueryLimitOffset                                    -- _1 KW["limit"] _2 KW[","] _3,
   HqlQueryLimitOffset.1:parameterized-sort               -- _1 _2,
   HqlQueryLimitOffset.1:parameterized-sort.1:"QueryRule" -- ,
   DslExp                                                 -- KW["~"] _1,
   HqlStatement                                           -- _1 KW[";"],
   HqlStatement.1:parameterized-sort                      -- _1 _2,
   HqlStatement.1:parameterized-sort.1:"DeleteStatement"  -- ,
   EmailCall                                              -- _1 KW["("] _2 KW[")"],
   EmailCall.2:iter-star-sep                              -- _1 KW[","],
   RenderEmailFunctionCall                                -- KW["renderemail"] KW["("] _1 KW[")"],
   EmailFunctionCall                                      -- KW["email"] KW["("] _1 KW[")"],
   EmailFunctionCall                                      -- KW["email"] _1,
   SendEmailFunctionCall                                  -- KW["sendemail"] KW["("] _1 KW[")"],
   RenderTemplateFunctionCall                             -- KW["rendertemplate"] KW["("] _1 KW[")"],
   ValidateTemplateFunctionCall                           -- KW["validatetemplate"] KW["("] _1 KW[")"],
   EventCall                                              -- KW["event"] KW["("] _1 KW[","] KW["["] _2 KW["]"] KW[")"],
   EventCall.2:iter-star-sep                              -- _1 KW[","],
   EventCallElement                                       -- KW["event"] KW["("] _1 KW[","] KW["["] _2 KW["]"] KW[")"],
   EventCallElement.2:iter-star-sep                       -- _1 KW[","],
   EventArg                                               -- _1 KW[":="] _2,
   AjaxStatement                                          -- _1 KW[";"],
   AjaxReplace                                            -- KW["replace"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxReplace                                            -- KW["replace"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxAppend                                             -- KW["append"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxAppend                                             -- KW["append"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxVisibility                                         -- KW["visibility"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxVisibility                                         -- KW["visibility"] KW["("] _1 KW[","] _2 KW[")"],
   Show                                                   -- KW["show"],
   Toggle                                                 -- KW["toggle"],
   Hide                                                   -- KW["hide"],
   AjaxRelocate                                           -- KW["relocate"] KW["("] _1 KW[")"],
   AjaxRestyle                                            -- KW["restyle"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxRestyle                                            -- KW["restyle"] KW["("] _1 KW[","] _2 KW[")"],
   AjaxClear                                              -- KW["clear"] KW["("] _1 KW[")"],
   AjaxClear                                              -- KW["clear"] KW["("] _1 KW[")"],
   AjaxRefresh                                            -- KW["refresh"] KW["("] KW[")"],
   AjaxRunScript                                          -- KW["runscript"] KW["("] _1 KW[")"],
   Placeholder                                            -- KW["placeholder"] _1 KW["{"] _2 KW["}"],
   Placeholder.2:iter-star                                -- _1,
   Placeholder                                            -- KW["placeholder"] _1 KW["{"] _2 KW["}"],
   Placeholder.2:iter-star                                -- _1,
   PlaceholderWithAjaxCall                                -- KW["placeholder"] _1 _2,
   PlaceholderWithAjaxCall                                -- KW["placeholder"] _1 _2,
   ThisCall                                               -- _1 KW["("] _2 KW[")"],
   ThisCall.2:iter-star-sep                               -- _1 KW[","],
   Call                                                   -- _1 KW["."] _2 KW["("] _3 KW[")"],
   Call.3:iter-star-sep                                   -- _1 KW[","],
   FieldAccess                                            -- _1 KW["."] _2,
   CollectionIndex                                        -- _1 KW["["] _2 KW["]"],
   Add                                                    -- _1 KW["+"] _2,
   Define                                                 -- KW["define"] _1 _2 KW["("] _3 KW[")"] _4 KW["{"] _5 KW["}"],
   Define.1:iter-star                                     -- _1,
   Define.3:iter-star-sep                                 -- _1 KW[","],
   Define.5:iter-star                                     -- _1,
   TemplateArgs                                           -- V  [H  [KW["requires"]] _1],
   TemplateArgs.1:iter-star-sep                           -- _1 KW[","],
   TemplateArg                                            -- _1 KW["("] _2 KW[")"],
   TemplateArg.2:iter-star-sep                            -- _1 KW[","],
   None                                                   -- ,
   LocalRedefine                                          -- KW["define"] _1 _2 KW["("] _3 KW[")"] KW["="] _4 _5,
   LocalRedefine.1:iter-star                              -- _1,
   LocalRedefine.3:iter-star-sep                          -- _1 KW[","],
   None                                                   -- ,
   LocalRedefineArgs                                      -- KW["("] KW["*"] KW[","] _1 KW[")"],
   LocalRedefineArgs.1:iter-sep                           -- _1 KW[","],
   Var                                                    -- _1,
   DefinePage                                             -- _1 KW["page"] _2 KW["("] _3 KW[")"] _4 KW["{"] _5 KW["}"],
   DefinePage.1:iter-star                                 -- _1,
   DefinePage.3:iter-star-sep                             -- _1 KW[","],
   DefinePage.5:iter-star                                 -- _1,
   DefineTemplate                                         -- _1 KW["template"] _2 KW["("] _3 KW[")"] _4 KW["{"] _5 KW["}"],
   DefineTemplate.1:iter-star                             -- _1,
   DefineTemplate.3:iter-star-sep                         -- _1 KW[","],
   DefineTemplate.5:iter-star                             -- _1,
   Page                                                   -- KW["page"],
   Email                                                  -- KW["email"],
   AjaxTemplate                                           -- KW["ajax"],
   Template                                               -- KW["template"],
   Feed                                                   -- KW["feed"],
   Local                                                  -- KW["local"],
   NoSpan                                                 -- KW["no-span"],
   TemplateModSpan                                        -- KW["span"],
   TemplateModInline                                      -- KW["inline"],
   TempateModSecure                                       -- KW["secure"],
   TemplateModNotSecure                                   -- KW["not-secure"],
   TemplateModOverride                                    -- KW["override"],
   TemplateDeprecated                                     -- KW["deprecated"],
   RequestScopeTemplate                                   -- KW["request"] _1,
   LocalScopeTemplate                                     -- KW["local"] _1,
   Text                                                   -- _1,
   FilterNoOrderByNoLimit                                 -- KW["where"] _1,
   FilterNoWhereNoLimit                                   -- KW["order"] KW["by"] _1,
   FilterNoLimit                                          -- KW["where"] _1 KW["order"] KW["by"] _2,
   FilterNoOrderBy                                        -- KW["where"] _1 _2,
   FilterNoWhere                                          -- KW["order"] KW["by"] _1 _2,
   FilterNoWhereNoOrderBy                                 -- _1,
   Filter                                                 -- KW["where"] _1 KW["order"] KW["by"] _2 _3,
   OrderNonSpecific                                       -- _1,
   OrderAscending                                         -- _1 KW["asc"],
   OrderDescending                                        -- _1 KW["desc"],
   Limit                                                  -- KW["limit"] _1 KW["offset"] _2,
   LimitNoOffset                                          -- KW["limit"] _1,
   LimitNoLimit                                           -- KW["offset"] _1,
   For                                                    -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 _4 KW[")"] KW["{"] _5 KW["}"] _6,
   For.5:iter-star                                        -- _1,
   ForNoFilter                                            -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] KW["{"] _4 KW["}"] _5,
   ForNoFilter.4:iter-star                                -- _1,
   ForAll                                                 -- KW["for"] KW["("] _1 KW[":"] _2 _3 KW[")"] KW["{"] _4 KW["}"] _5,
   ForAll.4:iter-star                                     -- _1,
   ForAllNoFilter                                         -- KW["for"] KW["("] _1 KW[":"] _2 KW[")"] KW["{"] _3 KW["}"] _4,
   ForAllNoFilter.3:iter-star                             -- _1,
   ForCount                                               -- KW["for"] KW["("] _1 KW[":"] KW["Int"] KW["from"] _2 KW["to"] _3 KW[")"] KW["{"] _4 KW["}"] _5,
   ForCount.4:iter-star                                   -- _1,
   ForSeparator                                           -- KW["separated-by"] KW["{"] _1 KW["}"],
   ForSeparator.1:iter-star                               -- _1,
   None                                                   -- ,
   SelectFromListNoPropsNoElems                           -- KW["select"] KW["("] _1 KW["from"] _2 KW[")"],
   SelectFromListNoElems                                  -- KW["select"] KW["("] _1 KW["from"] _2 KW[")"] KW["["] _3 KW["]"],
   SelectFromListNoElems.3:iter-star-sep                  -- _1 KW[","],
   SelectFromList                                         -- KW["select"] KW["("] _1 KW["from"] _2 KW[")"] KW["["] _3 KW["]"] KW["{"] _4 KW["}"],
   SelectFromList.3:iter-star-sep                         -- _1 KW[","],
   SelectFromList.4:iter-star                             -- _1,
   SelectFromListNoProps                                  -- KW["select"] KW["("] _1 KW["from"] _2 KW[")"] KW["{"] _3 KW["}"],
   SelectFromListNoProps.3:iter-star                      -- _1,
   IfTempl                                                -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"] KW["else"] KW["{"] _3 KW["}"],
   IfTempl.2:iter-star                                    -- _1,
   IfTempl.3:iter-star                                    -- _1,
   IfNoElseTempl                                          -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   IfNoElseTempl.2:iter-star                              -- _1,
   IfElseIfTempl                                          -- KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"] _3 _4,
   IfElseIfTempl.2:iter-star                              -- _1,
   IfElseIfTempl.3:iter                                   -- _1,
   IfElseIfTempl.4:opt                                    -- _1,
   ElseIfTempl                                            -- KW["else"] KW["if"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   ElseIfTempl.2:iter-star                                -- _1,
   ElseTempl                                              -- KW["else"] KW["{"] _1 KW["}"],
   ElseTempl.1:iter-star                                  -- _1,
   TemplateCase                                           -- KW["case"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   TemplateCase.1:iter-star-sep                           -- _1 KW[","],
   TemplateCase.2:iter-star                               -- _1,
   TemplateCaseAlt                                        -- _1 KW["{"] _2 KW["}"],
   TemplateCaseAlt.1:iter-star-sep                        -- _1 KW[","],
   TemplateCaseAlt.2:iter-star                            -- _1,
   TemplateCaseAltDefault                                 -- KW["default"] KW["{"] _1 KW["}"],
   TemplateCaseAltDefault.1:iter-star                     -- _1,
   TemplateCall                                           -- _1 KW["("] _2 KW[")"] KW["["] _3 KW["]"] _4,
   TemplateCall.2:iter-star-sep                           -- _1 KW[","],
   TemplateCall.3:iter-star-sep                           -- _1 KW[","],
   TemplateCallNoArgs                                     -- _1,
   TemplateCallNoBody                                     -- _1 KW["("] _2 KW[")"],
   TemplateCallNoBody.2:iter-star-sep                     -- _1 KW[","],
   TemplateCallNoAssigns                                  -- _1 KW["("] _2 KW[")"] _3,
   TemplateCallNoAssigns.2:iter-star-sep                  -- _1 KW[","],
   TemplateCallPropsNoBody                                -- _1 KW["("] _2 KW[")"] KW["["] _3 KW["]"],
   TemplateCallPropsNoBody.2:iter-star-sep                -- _1 KW[","],
   TemplateCallPropsNoBody.3:iter-star-sep                -- _1 KW[","],
   TemplateCallProps                                      -- _1 KW["["] _2 KW["]"],
   TemplateCallProps.2:iter-star-sep                      -- _1 KW[","],
   TemplateCallPropsNoArgs                                -- _1 KW["["] _2 KW["]"] _3,
   TemplateCallPropsNoArgs.2:iter-star-sep                -- _1 KW[","],
   TemplateCallBody                                       -- _1 _2,
   TemplateBody                                           -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   TemplateBody.1:iter-star                               -- _1,
   TemplateWith                                           -- KW["with"] KW["{"] _1 KW["}"],
   TemplateWith.1:iter-star                               -- _1,
   ArgDefine                                              -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   ArgDefine.2:iter-star-sep                              -- _1 KW[","],
   ArgDefine.3:iter-star                                  -- _1,
   NavigateCall                                           -- KW["navigate"] KW["("] _1 KW[")"] _2 KW["{"] _3 KW["}"],
   NavigateCall.2:iter-star                               -- _1,
   NavigateCall.3:iter-star                               -- _1,
   NavigateCall                                           -- KW["navigate"] KW["("] _1 KW[")"] KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   NavigateCall.2:iter-star-sep                           -- _1 KW[","],
   NavigateCall.3:iter-star                               -- _1,
   NavigateCall                                           -- KW["navigate"] _1 _2 KW["{"] _3 KW["}"],
   NavigateCall.2:iter-star                               -- _1,
   NavigateCall.3:iter-star                               -- _1,
   NavigateCall                                           -- KW["navigate"] _1 KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   NavigateCall.2:iter-star-sep                           -- _1 KW[","],
   NavigateCall.3:iter-star                               -- _1,
   PageCall                                               -- _1 KW["("] _2 KW[")"],
   PageCall.2:iter-star-sep                               -- _1 KW[","],
   Submit                                                 -- KW["action"] KW["("] _1 KW[","] _2 KW[")"] _3,
   Submit.3:iter-star                                     -- _1,
   Submit                                                 -- KW["action"] KW["("] _1 KW[","] _2 KW[")"] KW["["] _3 KW["]"],
   Submit.3:iter-star-sep                                 -- _1 KW[","],
   SubmitLink                                             -- KW["actionLink"] KW["("] _1 KW[","] _2 KW[")"] _3,
   SubmitLink.3:iter-star                                 -- _1,
   SubmitLink                                             -- KW["actionLink"] KW["("] _1 KW[","] _2 KW[")"] KW["["] _3 KW["]"],
   SubmitLink.3:iter-star-sep                             -- _1 KW[","],
   Submit                                                 -- KW["submit"] KW["("] _1 KW[","] _2 KW[")"] _3,
   Submit.3:iter-star                                     -- _1,
   Submit                                                 -- KW["submit"] KW["("] _1 KW[","] _2 KW[")"] KW["["] _3 KW["]"],
   Submit.3:iter-star-sep                                 -- _1 KW[","],
   SubmitLink                                             -- KW["submitlink"] KW["("] _1 KW[","] _2 KW[")"] _3,
   SubmitLink.3:iter-star                                 -- _1,
   SubmitLink                                             -- KW["submitlink"] KW["("] _1 KW[","] _2 KW[")"] KW["["] _3 KW["]"],
   SubmitLink.3:iter-star-sep                             -- _1 KW[","],
   SubmitElem                                             -- KW["submit"] _1 _2 KW["{"] _3 KW["}"],
   SubmitElem.2:iter-star                                 -- _1,
   SubmitElem.3:iter-star                                 -- _1,
   SubmitElem                                             -- KW["submit"] _1 KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   SubmitElem.2:iter-star-sep                             -- _1 KW[","],
   SubmitElem.3:iter-star                                 -- _1,
   SubmitLinkElem                                         -- KW["submitlink"] _1 _2 KW["{"] _3 KW["}"],
   SubmitLinkElem.2:iter-star                             -- _1,
   SubmitLinkElem.3:iter-star                             -- _1,
   SubmitLinkElem                                         -- KW["submitlink"] _1 KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   SubmitLinkElem.2:iter-star-sep                         -- _1 KW[","],
   SubmitLinkElem.3:iter-star                             -- _1,
   DownloadLink                                           -- KW["downloadlink"] _1 _2 KW["{"] _3 KW["}"],
   DownloadLink.2:iter-star                               -- _1,
   DownloadLink.3:iter-star                               -- _1,
   DownloadLink                                           -- KW["downloadlink"] _1 KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   DownloadLink.2:iter-star-sep                           -- _1 KW[","],
   DownloadLink.3:iter-star                               -- _1,
   OutputImage                                            -- KW["outputimage"] _1 _2 KW["{"] _3 KW["}"],
   OutputImage.2:iter-star                                -- _1,
   OutputImage.3:iter-star                                -- _1,
   OutputImage                                            -- KW["outputimage"] _1 KW["["] _2 KW["]"] KW["{"] _3 KW["}"],
   OutputImage.2:iter-star-sep                            -- _1 KW[","],
   OutputImage.3:iter-star                                -- _1,
   ActionCall                                             -- _1 KW["("] _2 KW[")"],
   ActionCall.2:iter-star-sep                             -- _1 KW[","],
   InlineAction                                           -- KW["action"] _1,
   PropertySubmit                                         -- _1 KW[":"] _2,
   PropertySubmit                                         -- _1 KW[":="] _2,
   PropertySubmit                                         -- _1 KW["="] _2,
   PropertyAssignment                                     -- _1 KW[":"] _2,
   PropertyAssignment                                     -- _1 KW[":="] _2,
   PropertyAssignment                                     -- _1 KW["="] _2,
   TemplateCallPropertyAjax                               -- KW["ajax"],
   TemplateCallPropertySecure                             -- KW["secure"],
   TemplateCallPropertyIgnoreValidation                   -- KW["ignore-validation"],
   TemplateCallPropertyNotSecure                          -- KW["not-secure"],
   TemplateCallPropertyNotNull                            -- KW["not null"],
   InitAction                                             -- KW["init"] _1,
   DataBindAction                                         -- KW["databind"] _1,
   RenderAction                                           -- KW["render"] _1,
   ValidateAction                                         -- KW["validate"] _1,
   Action                                                 -- KW["action"] _1 _2 KW["("] _3 KW[")"] _4,
   Action.1:iter-star                                     -- _1,
   Action.3:iter-star-sep                                 -- _1 KW[","],
   ActionModifierIgnoreValidation                         -- KW["ignore-validation"],
   QualifiedElementsCall                                  -- _1 KW[".elements"],
   Module                                                 -- KW["module"] _1 _2,
   Module.2:iter-star                                     -- _1,
   Entity                                                 -- KW["entity"] _1 KW["{"] _2 KW["}"],
   Entity.2:iter-star                                     -- _1,
   Property                                               -- _1 KW[":"] _2,
   Type                                                   -- _1,
   Qualified                                              -- _1 KW["."] _2,
   ApplicationDefs                                        -- KW["application"] _1 _2 _3,
   ApplicationDefs.2:iter                                 -- _1,
   ApplicationDefs.3:iter-star                            -- _1,
   Application                                            -- KW["application"] _1 _2,
   Application.2:iter-star                                -- _1,
   Description                                            -- KW["description"] KW["{"] _1 KW["}"],
   Description.1:iter-star                                -- _1,
   Note                                                   -- KW["note"] KW["{"] _1 KW["}"],
   Note.1:iter-star                                       -- _1,
   Module                                                 -- KW["module"] _1 _2,
   Module.2:iter-star                                     -- _1,
   ModuleDefs                                             -- KW["module"] _1 _2 _3,
   ModuleDefs.2:iter                                      -- _1,
   ModuleDefs.3:iter-star                                 -- _1,
   Imports                                                -- KW["imports"] _1
]