application outliner

//generic imports
imports widgets
imports tree
imports masterdetail
imports popup

//application specific imports
imports data
imports documentmanagement
imports toolbar
imports nodeview


section pages

define page root() {
  var d: Document := null;
  outliner_contents(d)
}

define page outliner(doc: Document) {
  outliner_contents(doc)
}

define outliner_contents(doc: Document) {
  //a hook for the popup windows
  placeholder popup {}
  
  container[id:= header] {
    "outliner"
    toolbar(doc)
  }

  navigate()[onclick := action { visibility (header , toggle); }]{ "^^^" }
  spacer

  main(doc)
  
  spacer
  "application generated by WebDSLx"
}

define main(doc: Document) {
  if (doc == null) {
    "(No document loaded)" 
  }
  else {
    masterdetail(doc.root) with {

      detailview(item: TreeItem) {
        detailView(item)
      }
      treeview(item: TreeItem) {
        //dispatch to  proper view
               if (item isa HeaderNode) { treeviewHeader(item as HeaderNode) }
        else { if (item isa TextNode)   { treeviewText  (item as TextNode) }
        else { if (item isa ImageNode)  { treeviewImage (item as ImageNode) }
        else { "Error: unsupported node type" }  }  }
      }
    }
    
  }
} 
