all :
	$(MAKE) -C org.strategoxt.imp.metatooling all
	$(MAKE) -C org.strategoxt.imp.editors.stratego all
	$(MAKE) -C org.strategoxt.imp.editors.strategojava all
	$(MAKE) -C org.strategoxt.imp.editors.php all

sdf2imp :
	$(MAKE) -C org.strategoxt.imp.metatooling sdf2imp

