all :
	$(MAKE) -C org.strategoxt.imp.metatooling all
	$(MAKE) -C org.strategoxt.imp.runtime all
	$(MAKE) -C org.strategoxt.imp.editors.editorservice all

check :
	$(MAKE) -C org.strategoxt.imp.metatooling check
