all :
	$(MAKE) -C org.strategoxt.imp.metatooling all
	$(MAKE) -C org.strategoxt.imp.runtime all
	$(MAKE) -C org.strategoxt.imp.editors.editorservice all

check : all
	$(MAKE) -C org.strategoxt.imp.metatooling check

clean :
	$(MAKE) -C org.strategoxt.imp.metatooling clean
	$(MAKE) -C org.strategoxt.imp.editors.editorservice clean
