module image

section templates


define viewImage(item: ImageNode) {
  block[id := viewImage, class :="scopediv viewText"] {
    if (item.image== null) {
      navigate(editImage(item, getDocument(item))) {
        "[click to provide an image]"
      }
    }
    else {
      output(item.image)
    }
  }
}

define page editImage(item: ImageNode, doc: Document) {
  loadCSS("outliner.css")
  loadCSS("widgets.css")
  footerLayout("100px")[width:="800px"] with {
    contents() {
      collapseUp() {
          toolbar(doc)
      }
      popup("Select an image to upload") {
        form {
          input(item.image)
          action("save",save())[id:= submit,classic:= true]
        }      
      }
    }
    footer() {
      spacer 
      container[id:= statusBar, style:="height: 20px; width:100%; float: bottom"] { " Loaded." } 
      spacer
      "application generated by WebDSLx"
    }
  }
  action save() {
    //message("Image uploaded");
    //var x: Document := getDocument(item);
    return outliner(doc);
  }	
}
