package webdsl.safari.parser;

import java.io.IOException;

import org.spoofax.jsglr.InvalidParseTableException;
import org.strategoxt.imp.runtime.parser.SGLRParseController;
import org.strategoxt.imp.runtime.parser.tokens.SGLRTokenKindManager;

import parser.ast.WebDSLAstNodeFactory;

import webdsl.Activator;

/**
 * Parse controller for the WebDSL language.
 * 
 * @note This file should be generated by a wizard.
 * 
 * @author Lennart Kats <L.C.L.Kats add tudelft.nl>
 */
public class WebDSLParseController extends SGLRParseController {

	public WebDSLParseController() 
			throws IOException, InvalidParseTableException {
		
		// TODO: Grammar-specific node factory and token kind manager
		
		super(new WebDSLAstNodeFactory(), new SGLRTokenKindManager(), Activator.class.getResourceAsStream("/syntax/WebDSL.tbl"), null);
	}
	
	// Methods that should be overridden by the generator
	
	@Override
	public String getSingleLineCommentPrefix() {
		return super.getSingleLineCommentPrefix();
	}
}
