package webdsl.safari.parser;

import java.io.IOException;

import org.spoofax.jsglr.InvalidParseTableException;
import org.strategoxt.imp.runtime.parser.SGLRParseController;
import org.strategoxt.imp.runtime.parser.ast.SGLRAstNodeFactory;

import webdsl.Activator;

/**
 * Parse controller for the WebDSL language.
 * 
 * @note This file should be generated by a wizard.
 * 
 * @author Lennart Kats <L.C.L.Kats add tudelft.nl>
 */
public class WebDSLParseController extends SGLRParseController {

	public WebDSLParseController() 
			throws IOException, InvalidParseTableException {
		
		super(new SGLRAstNodeFactory(), Activator.class.getResourceAsStream("/syntax/WebDSL.tbl"));
	}
}
